GET localhost:8080/api/household

### Get a user with the given id
GET localhost:8080/api/user/3
Accept: application/json

### Get all users
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/user/1

###
PATCH http://localhost:8080/api/task/51/update
Content-Type: application/json
#

{ "id" : 51 , "title": "go boom boom" }

###
#PUT http://localhost:8080/api/users
#Content-Type: application/json
# Check that new user was added
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/household/tasks

###
GET http://localhost:8080/api/tasks

###
GET http://localhost:8080/api/household/tasks

###
PATCH http://localhost:8080/api/task/29/update
Content-Type: text/json

{
  "done": true
}
###
GET http://localhost:8080/api/task/28